"""
Configuration package for Error Autopsy.

Provides centralized access to all application settings.
"""

from config.settings import (
    ASSETS_DIR,
    AVOIDABLE_ERROR_TYPES,
    BASE_DIR,
    CSS_FILE,
    DATA_DIR,
    DATE_FORMAT_DISPLAY,
    DATE_FORMAT_ISO,
    DAYS_PER_MONTH,
    DEFAULT_DIFFICULTY,
    DEFAULT_ERROR_TYPE,
    DEFAULT_EXAM_TYPE,
    DIFFICULTY_LEVELS,
    ENEM_SECTIONS,
    ERROR_LOG_FILE,
    ERROR_TYPES,
    EXAM_PACE_BENCHMARKS,
    EXAM_SECTION_DEFS,
    EXAM_SUBJECTS,
    EXAM_TYPES,
    SAT_SECTIONS,
    AccuracyZone,
    AppConfig,
    ChartConfig,
    Colors,
    DifficultyLevel,
    ErrorType,
    ExamType,
    PaceZone,
    TimeFilter,
    get_pace_benchmark,
    get_sections_for_exam,
    get_subjects_for_exam,
)

__all__ = [
    "AccuracyZone",
    "AppConfig",
    "ChartConfig",
    "Colors",
    "DifficultyLevel",
    "ErrorType",
    "ExamType",
    "PaceZone",
    "TimeFilter",
    "ASSETS_DIR",
    "AVOIDABLE_ERROR_TYPES",
    "BASE_DIR",
    "CSS_FILE",
    "DATA_DIR",
    "DATE_FORMAT_DISPLAY",
    "DATE_FORMAT_ISO",
    "DAYS_PER_MONTH",
    "DEFAULT_ERROR_TYPE",
    "DEFAULT_DIFFICULTY",
    "DEFAULT_EXAM_TYPE",
    "DIFFICULTY_LEVELS",
    "ENEM_SECTIONS",
    "ERROR_LOG_FILE",
    "ERROR_TYPES",
    "EXAM_PACE_BENCHMARKS",
    "EXAM_SECTION_DEFS",
    "EXAM_SUBJECTS",
    "EXAM_TYPES",
    "SAT_SECTIONS",
    "get_pace_benchmark",
    "get_sections_for_exam",
    "get_subjects_for_exam",
]
